### ISSUE TITLE
Where can I download latest release?

### ISSUE THREAD

**Issue by odil24** [shocker-0x15/VLR#4]
Hi. I'm interested on the project and would like to testout. But where can i download it? Any link?
Thanks.

**Comment by shocker-0x15** [comment]
Hello,
there is no explicit release package.
You need to build master branch by yourself.

Best

**Comment by odil24** [comment]
Hi. But how to do this? Is there any doc on how to do it or FAQ?

Regards,
Odilkhan Yakubov.

вс, 20 Сен 2020, 18:13 shocker-0x15 <notifications@github.com>:

**Comment by shocker-0x15** [comment]
This is just a hobby project and currently has no doc/FAQ.
If you use Visual Studio, just open VLR.sln, otherwise use CMake to generate something for compiling the VLR.
You need CUDA and OptiX SDK to be installed.

**Comment by odil24** [comment]
Ok. Thank you for reply.

Regards,
Odilkhan Yakubov.

пн, 21 Сен 2020, 1:08 shocker-0x15 <notifications@github.com>:
