### ISSUE TITLE
Difference between VLR and Optix wrapper

### ISSUE THREAD

**Issue by ib00** [shocker-0x15/VLR#5]
What's the difference between VLR project and your other Optix wrapper?

**Comment by shocker-0x15** [comment]
VLR is a renderer based on my OptiX wrapper, so this is an application.
OptiX Utility is a wrapper library with sample code demonstrating how to use the library.

The master branch of VLR is based on an old version of OptiX (6.0) and wrapper, while OptiX7_RE branch is based on almost recent version and still WIP.

**Comment by ib00** [comment]
So, you could write VLR-like renderer using Optix_Utility?

**Comment by shocker-0x15** [comment]
Yes you can.
VLR is already based on OptiX_Utility.

**Comment by shocker-0x15** [comment]
Sorry, my first comment was a bit incorrect.
The master branch of VLR doesn't use my wrapper, it just uses the official C++ interface.

**Comment by ib00** [comment]
I want to write my own toy renderer, so Optix_Wrapper seems what I am looking for.

Are you aware of a similar wrapper (functionality-wise) for Vulkan?

**Comment by shocker-0x15** [comment]
I'm not familiar with Vulkan. I think it is conceptually possible to make a similar wrapper for Vulkan or DX12 but resource management could be mess or complicated.
CUDA/OptiX allow us to use a raw pointer in a kernel and language (CUDA C++) is sophisticated compared to HLSL/GLSL. I like to use CUDA unless we want to distribute a multi-platform software.
