### ISSUE TITLE
Question: Ubuntu support

### ISSUE THREAD

**Issue by bipul-mohanto** [shocker-0x15/VLR#6]
Hello @shocker-0x15,

both of your VLR renderer and [OptiX_Utility](https://github.com/shocker-0x15/OptiX_Utility) is windows-based. However, is it possible to run these on Linux (Ubuntu) with some minor modification? Do you have any plan to extend your `VLR rendering engine` for Linux (Ubuntu)? 

If I am not wrong, `VLR` is a rendering engine, and `OptiX_Utility` is a OptiX wrapper library as `Project-OWL` by Ingo Wald, right?

**Comment by shocker-0x15** [comment]
I didn't test VLR on Linux at all. There must be some code to extend to run VLR on Linux, but I guess those should be relatively minor modifications. I don't have a plan to extend VLR to Linux for now by myself.

Regarding the last question, you are correct.

**Comment by bipul-mohanto** [comment]
Thanks @shocker-0x15 for your reply. I am just a beginner in OptiX world, so I may have some silly questions. 

*  To my best knowledge, VLR is the first OptiX based rendering engine publicly available. At the beginning of VLR, you mentioned 

> VLR is a GPU Monte Carlo ray tracing renderer using NVIDIA OptiX 7

Doesn't that make **VLR is a GPU based path tracing renderer?** Because so far, I know, ` Monte Carlo ray tracing = uni-directional path tracing`.  Please correct me if I am wrong. 
* You did not use OptiX_Utility wrapper library in VLR (what I understand from reading the github readme instructions). So, **OptiX_Utility and VLR are totally 2 different projects from you and have no relation to each other?** 
*  In VLR you have used `libVLR` with relevant files and mentioned that is another `C++ wrapper library`. So, is this `libVLR` only designed for `VLR`?

**Comment by shocker-0x15** [comment]
In my understanding, Monte Carlo Ray Tracing is a generic name for light transport algorithms including path tracing, bidirectional path tracing, metropolis light transport and possibly photon mapping and its variants (progressive photon mapping and VCM/UPS) , etc.

- VLR is using OptiX_Utility.
- libVLR is the renderer and that is VLR itself, the body of this repository. Another project HostProgram is there. It is literally a host program just to run VLR.

**Comment by bipul-mohanto** [comment]
Thanks a lot, it's all clear now.
